services:
  - type: web
    name: backend-php
    env: php
    plan: free
    buildCommand: 'composer install --working-dir=backend'
    startCommand: 'php -S 0.0.0.0:$PORT -t backend/public'

  - type: static
    name: frontend-static
    plan: free
    buildCommand: ''
    staticPublishPath: frontend

  - type: web
    name: websocket-server
    env: php
    plan: free
    buildCommand: 'composer install --working-dir=backend'
    startCommand: 'php backend/public/ws-server.php'
